#define IDI_EVERON                      101
#define IDD_SETTINGS                    102
#define IDD_ABOUT                       103
#define IDC_STATIC                      -1
#define IDC_LANGUAGE_LABEL              1000
#define IDC_PERIOD_EDIT                 1001
#define IDC_KEY_COMBO                   1002
#define IDC_KEEPDISPLAY_CHECK           1003
#define IDC_AUTOSTART_CHECK             1004
#define IDC_LANGUAGE_COMBO              1005
#define IDC_HOTKEY_ENABLE_CHECK         1006
#define IDC_HOTKEY_COMBO                1007
#define IDC_GENERAL_GROUP               1008
#define IDC_HOTKEYS_GROUP               1009
#define IDC_PERIOD_LABEL                1010
#define IDC_PERIOD_SECONDS_LABEL        1011
#define IDC_KEYPRESS_LABEL              1012
#define IDC_HOTKEY_LABEL                1013
#define IDC_TIMER_GROUP                 1014
#define IDC_TIMER_INDEFINITE            1015
#define IDC_TIMER_DURATION              1016
#define IDC_TIMER_DURATION_EDIT         1017
#define IDC_TIMER_DURATION_LABEL        1018
#define IDC_TIMER_UNTIL                 1019
#define IDC_TIMER_UNTIL_TIME            1020
#define IDC_NOTIFY_TOGGLE_CHECK         1021
#define IDC_ABOUT_VERSION               1022
#define IDC_ABOUT_TAGLINE               1023
#define IDC_ABOUT_AUTHOR                1024
#define IDC_ABOUT_LICENSE               1025
#define IDC_ABOUT_LINK                  1026
#define IDM_TOGGLE                      40001
#define IDM_SETTINGS                    40002
#define IDM_ABOUT                       40003
#define IDM_EXIT                        40004
