#pragma once

#define VER_MAJOR 2
#define VER_MINOR 8
#define VER_PATCH 0
#define VER_BUILD 0

#define EVERON_STRINGIZE_INNER(value) #value
#define EVERON_STRINGIZE(value) EVERON_STRINGIZE_INNER(value)
#define EVERON_WIDEN_INNER(value) L##value
#define EVERON_WIDEN(value) EVERON_WIDEN_INNER(value)

#define VER_FILEVERSION VER_MAJOR,VER_MINOR,VER_PATCH,VER_BUILD
#define VER_PRODUCTVERSION VER_FILEVERSION
#define VER_FILEVERSION_STR EVERON_STRINGIZE(VER_MAJOR) "." EVERON_STRINGIZE(VER_MINOR) "." EVERON_STRINGIZE(VER_PATCH) "." EVERON_STRINGIZE(VER_BUILD)
#define VER_PRODUCTVERSION_STR VER_FILEVERSION_STR

#if VER_PATCH == 0
#define VER_VERSION_STR EVERON_STRINGIZE(VER_MAJOR) "." EVERON_STRINGIZE(VER_MINOR)
#else
#define VER_VERSION_STR EVERON_STRINGIZE(VER_MAJOR) "." EVERON_STRINGIZE(VER_MINOR) "." EVERON_STRINGIZE(VER_PATCH)
#endif

#define VER_VERSION_STR_W EVERON_WIDEN(VER_VERSION_STR)
#define VER_FILEVERSION_STR_W EVERON_WIDEN(VER_FILEVERSION_STR)
